### PR TITLE
Add AIX support

### PR DESCRIPTION
**Pull request by Helflym**
This commit adds support for a new Golang GOOS: AIX.

### CODE REVIEW

**Comment by trdyer** [comment]
Is there any timeline on this or any blockers?

**Comment by amdprophet** [comment]
I've verified that this change works for https://github.com/sensu/sensu-go. We'd love to see this get merged!

**Comment by jtwatson** [comment]
What are the chances that we can get this PR merged? 
I have tested and it works well for me on AIX!

**Comment by jwatson-gcu** [comment]
@spf13 I was hoping we could get some movement on this. Do you have a moment to look this over?

**Pull request merged**
