### PR TITLE
MemMapFs, CopyOnWriteFs: Require parent directory on creates

### PR DESCRIPTION
**Pull request by JohnStarich**
Fixes https://github.com/spf13/afero/issues/149 https://github.com/spf13/afero/issues/209

With this PR, now `MemMapFs` and `CopyOnWriteFs` only allow new files or directories if the parent exists and is a directory. Even though this is desirable (since it follows `OsFs` behavior), this likely breaks backward compatibility with v1 of afero. I had to fix several tests that relied on previous behavior.

@spf13 Is there a procedure on candidate PRs for afero@v2?

Also I'd be happy to squash related commits, if that makes it easier to review 😄

### CODE REVIEW

**Comment by spf13** [comment]
I don't think we've established a procedure yet for afero v2.

**Comment by JohnStarich** [comment]
Ok, thanks for your quick response 👍

Is this PR a good candidate for v2? Should I base this on a new v2 branch, perhaps?

(I see Windows failed some tests, probably filepath related. I’ll fix those soon, too.)

**Comment by spf13** [comment]
I think it's a candidate for v2. I don't think we have a solid plan for the
v2 yet though and that would be a requirement for that branch. I think we
should spend some time over the next few weeks forming a v2 plan.

**Comment by JohnStarich** [comment]
@kargakis Thanks for the new `breaking-change` label!

Ok, just fixed the tests on Windows so all set there 👍 Let me know how I can help with any v2 preparation 🙂

**Comment by JohnStarich** [comment]
Initially, I decided to fork and maintain [that fork](https://github.com/JohnStarich/afero) with my fixes. It's been a year now, so I've created a library of my own ([`hackpadfs`](https://github.com/hack-pad/hackpadfs)), which takes advantage of 1.16's new interface-oriented FS design.

I've got a solution now, so I'll go ahead and close. Feel free to re-open and merge later if you like. 🙂

**Pull request closed without merging**
