### PR TITLE
Add Symlinker, Readlinker, EvalSymlinks.

### PR DESCRIPTION
**Pull request by mpictor**
Related: issue #174 

This PR improves symlink-related functionality in all afero fs types except the memory fs (still not sure what to do there).

Note that I haven't tested anywhere but linux.

### CODE REVIEW

**Comment by mpictor** [comment]
Appveyor looks to be a windows-specific failure; anyone here on windows care to look at that?

Travis-ci acts as if `strings.ReplaceAll()` doesn't exist. Not sure what to make of that.

**Comment by 200sc** [comment]
strings.ReplaceAll was added in 1.12, If travis is using 1.9 or 1.10 as the yaml specifies

**Comment by mpictor** [comment]
> strings.ReplaceAll was added in 1.12, If travis is using 1.9 or 1.10 as the yaml specifies

Thought sure I was using it ages ago.. :confused:

**Comment by therealplato** [comment]
- `filepath` implementations [(e.g.)](https://godoc.org/path/filepath#EvalSymlinks) or tests may be relevant
- one approach to avoid hardcoding unix path separators in testcases while maintaining cases for leading/missing/duplicate separators:
```diff
{
  name:      "1",
-  path:      "/test/path",
-  link:      "../a//b",
-  want:      "/test/a/b",
+  path:      []string{"", "test", "", "path"},
+  link:      []string{"..", "", "a", "", "", "b"},
+  want:      []string{"", "test", "", "a", "", "b"},
  expectErr: false,
},

```

**Comment by mpictor** [comment]
OSX is failing with 
```
    	link_test.go:215: lstat private/var: no such file or directory
```
... but I don't see where that could be coming from - no strings that I see in the code match `private` or `var`.

**Comment by mpictor** [comment]
OSX is failing with 
```
    	link_test.go:215: lstat private/var: no such file or directory
```
... but I don't see where that could be coming from - no strings that I see in the code match `private` or `var`.

**Comment by mpictor** [comment]
Closing until I get a chance to fix this.

**Pull request closed without merging**
