### PR TITLE
rename mem fs with descendants

### PR DESCRIPTION
**Pull request by hanagantig**
fix for issue [#141](https://github.com/spf13/afero/issues/141)
Please check it. This bug needs to be fixed.

### CODE REVIEW

**Comment by hanagantig** [comment]
@bep hi, this is an old pull request for https://github.com/spf13/afero/issues/141 issue.
I updated the branch and resolved conflicts. If you have time could you look at it please, it would be appreciated.

**Comment by hanagantig** [comment]
@bep any comments or suggestions here please

**Comment by bep** [comment]
@hanagantig sorry for the delay; this looks correct, but it needs to be rebased with master. If you do that and ping me again, I will merge.

**Comment by hanagantig** [comment]
@bep Thanks a lot. I just pushed it without merge commits. Could you please have a look?

**Comment by bep** [comment]
@hanagantig there's a staticcheck error there that should be easy to fix.

**Comment by hanagantig** [comment]
@bep `unnecessary assignment` static check error fixed

**Comment by hanagantig** [comment]
@bep can we merge this please ?

**Comment by hanagantig** [comment]
@bep your attention is required. Could you please proceed with checks ?

**Comment by hanagantig** [comment]
@bep thank you so much :pray:

**Pull request merged**
