### PR TITLE
Fix pagination for Composite Fs File.Readdir() and File.Readdirnames()

### PR DESCRIPTION
**Pull request by victpork**
Make File.Readdir() and File.Readdirnames() behavior closer to their counterparts in os.File. Giving a c >No. of files in directory will not panic, and -1 will not change the internal offset. And subsequent call will give io.EOF as expected.

### CODE REVIEW

**Comment by mkishere** [comment]
Hi anyone looking at this? I don't know if it still relevant though

**Comment by mkishere** [comment]
Hi @bep ? Not sure if this is still relevant,  if yes, care to do a review?

**Comment by kargakis** [comment]
Needs a rebase

**Comment by kargakis** [comment]
Feel free to reopen if you plan to rebase.

**Pull request closed without merging**
