### PR TITLE
Add SftpFs beta backend

### PR DESCRIPTION
**Pull request by xor-gate**
As discussed in #47, have fun :-)

### CODE REVIEW

**Comment by xor-gate** [comment]
It seems continues integration chokes on the test, i have no real clue how to make this actually work. The problem is we need to spawn a sftp server and test against it. Or remove the "example/test" completely.

**Comment by xor-gate** [comment]
@mbertschler you are right I fixed up the test and now spawn a Sftp server and generate the RSA host key :+1:

**Comment by mbertschler** [comment]
@xor-gate the Sftp server in the tests is a good idea :+1:.
I have not tested it yet but I think this is ready to merge as an experimental feature. I will probably play around with it in the next days, and also see if this FS works with our existing tests.

**Comment by xor-gate** [comment]
Thank you @mbertschler. And yes having the sftp server stub in the test makes sure with the CI tests that everything is still functional.

**Pull request merged**
