### PR TITLE
Fix data race in InMemoryFile by locking Read and Write.

### PR DESCRIPTION
**Pull request by jaqx0r**
Adds a sync.Mutex to the InMemoryFile struct to lock f.data field access in the Read and Write methods.

Also locks access to f.closed in Open and Close methods.

Fixes: #8.

### CODE REVIEW

**Comment by spf13** [comment]
I tried merging this and it couldn't because of #5. I tried to reset to before that commit and apply this one cleanly and it didn't work. Then I tried just manually merging it one commit at a time which worked, but resulted in deadlocks. 

Thanks for the contribution. I'd love to get it in, but I think this one needs to be cleaned up a bit more so we can apply it cleanly. I'd pull from master and rebase this to get it in the right shape. 

Here's the output I got once it was merged. It's quite possible I made a mistake with the manual merging that caused it.

```
 go test ./...
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.RunTests(0x3a01c8, 0x48d1a0, 0x7, 0x7, 0x533c148f93fe7001)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208030370, 0x497da0)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/spf13/afero/_test/_testmain.go:64 +0x1d5

goroutine 5 [semacquire]:
sync.(*Mutex).Lock(0xc2080122a0)
	/usr/local/Cellar/go/1.4/libexec/src/sync/mutex.go:66 +0xd3
github.com/spf13/afero.(*InMemoryFile).Read(0xc2080122a0, 0x498670, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memfile.go:123 +0x168
github.com/spf13/afero.TestRead0(0xc208068120)
	/Users/spf13/gopath/src/github.com/spf13/afero/fs_test.go:59 +0x648
testing.tRunner(0xc208068120, 0x48d1a0)
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:555 +0xa8b
FAIL	github.com/spf13/afero	0.006s
```

**Comment by bep** [comment]
In this case, I'm pretty sure Go's RWMutex is a better choice.

**Comment by jaqx0r** [comment]
Ok, I'll re upload the pr, i think I just accidentally uploaded a conflict
I created and fixed locally.

**Comment by jaqx0r** [comment]
Björn, yes probably but my use case is test code where I don't care about
performance, only correct mess, so I didn't bother to add read locking.
Premature optimization etc.

**Comment by jaqx0r** [comment]
Sorry, Bjørn.

**Comment by jaqx0r** [comment]
Please, take another look.  It seems I fixed the conflict in the other branch and failed to push upstream.

**Comment by jaqx0r** [comment]
I'm going to assume this pull is OK as you granted me access to the repo.

**Comment by bep** [comment]
Assuming it's OK when there is a discussion going on is ... not perfectly OK. Remember, there are other projects pulling in this lib.

**Comment by jaqx0r** [comment]
With respect, this was a small improvement to fix a clear bug, and you are
proposing another improvement on top of that. My merge doesn't preclude
another, better, fix on top of that in the future.

**Comment by bep** [comment]
With respect,

When your "small improvement" is a set of eight commits (!) in total, you should let others do the merging. I have cleaned up this mess now.

**Comment by jaqx0r** [comment]
Bjørn,

I don't know who you are or your relationship to this project, but in our
discussion I am rapidly coming to the conclusion that you have commit
access to this repository.  I am sorry for offending you and merging my
commit before you had a chance to comment on it, given your level of
responsibility.

In my defence, I sent these PRs a month ago, and heard nothing from anyone
until the other day when both you and spf13 appeared, merged one PR, and
granted me write access.  With no other information to go on, I had to
assume that this was a sign that spf13 was an intermittent maintainer, and
the write access was granted as he wasn't sure when he'd be able to merge
the other once I'd fixed the conflicts.  I had no idea that you were even a
contributor, nor that there were non-github-based merge processes.

The eight commits in a branch is hardly something to balk at.  I was trying
to maintain two bugfixes separately so they could be merged cleanly, and
obviously failed, but in the process generated several iterations on the
result.  I maintain that collapsing eight commits into one is merely
cosmetic, loses information into the development process that arrives at
the resulting PR, and thus is an unmotivated burden on humans.

To address these issues in the future, I have some ideas:
* document the merge process and other formalities in the repo so that new
committers can understand the processes and policies of the project
* introduce yourself to a new contributor at the start of a discussion, so
they understand who the members are (Note the README contains only spf13,
and now myself.)
* do not grant write access to new contributors immediately on the basis
that they fixed two bugs, without having them acknowledge the existence of
processes
* revoke my write access to the repository, as we clearly have different
ideas on the preservation of commit history.

I am of couse happy to send you PRs in the future if I discover more issues.

**Comment by bep** [comment]
I will end with this:

* I'm a contributor on the Hugo project.
* Hugo uses Afero
* As the current build system in Go works, new commits in Afero will be included in new builds of Hugo
* So, to trust the quality of Hugo you must also trust the quality of its dependencies
* Just looking at the commit log after your merge gets me to question the quality of this library. It was a mess. There were two commits just to get your name on the list of contributors. Looking at the PR as one or two commits, I can see that it's fine. You may feel that a messy commit log is just cosmetics, but I disagree.

Lets leave it at that.

**Pull request merged**
